// export const busBookingsData = [
//   {
//     id: 1,
//     residentName: "John Doe",
//     roomNumber: "101",
//     busRoute: "Route A",
//     DepartureDateAndTime: "2024-07-01 • 08:00AM",
//     status: "Pending",
//   },
//   {
//     id: 2,
//     residentName: "Jane Smith",
//     roomNumber: "102",
//     busRoute: "Route B",
//     DepartureDateAndTime: "2024-07-01 • 09:00AM",
//     status: "Confirmed",
//   },
//   {
//     id: 3,
//     residentName: "Alice Johnson",
//     roomNumber: "103",
//     busRoute: "Route C",
//     DepartureDateAndTime: "2024-07-02 • 10:00AM",
//     status: "Pending",
//   },
//   {
//     id: 4,
//     residentName: "Bob Brown",
//     roomNumber: "104",
//     busRoute: "Route D",
//     DepartureDateAndTime: "2024-07-02 • 11:00AM",
//     status: "Confirmed",
//   },
//   {
//     id: 5,
//     residentName: "Charlie Davis",
//     roomNumber: "105",
//     busRoute: "Route E",
//     DepartureDateAndTime: "2024-07-03 • 08:30AM",
//     status: "Pending",
//   },
//   {
//     id: 6,
//     residentName: "David Wilson",
//     roomNumber: "106",
//     busRoute: "Route F",
//     DepartureDateAndTime: "2024-07-03 • 09:30AM",
//     status: "Confirmed",
//   },
//   {
//     id: 7,
//     residentName: "Emily Clark",
//     roomNumber: "107",
//     busRoute: "Route G",
//     DepartureDateAndTime: "2024-07-04 • 10:30AM",
//     status: "Pending",
//   },
//   {
//     id: 8,
//     residentName: "Frank Harris",
//     roomNumber: "108",
//     busRoute: "Route H",
//     DepartureDateAndTime: "2024-07-04 • 11:30AM",
//     status: "Confirmed",
//   },
// ];
