export const notifications = [
  {
    id: 1,
    icon: "/svg/yellowInfo.svg",
    title: {
      en: "Your bus departs at 10:00 AM.",
      es: "Su autobús sale a las 10:00 AM.",
      fr: "Votre bus part à 10h00.",
      ar: "حافلتك تغادر الساعة 10:00 صباحًا",
      ps: "ستاسې بس د 10:00 بجو پرانستل کېږي.",
      pt: "Seu ônibus parte às 10:00.",
      uk: "Ваш автобус відправляється о 10:00.",
      ha: "Baburinka zai tashi a 10:00 na safe.",
      ka: "თქვენი ავტობუსი გავა 10:00 საათზე.",
      ge: "თქვენი ავტობუსი გადის 10:00 საათზე.",
    },
    description: {
      en: "Please be ready at the pickup point in 30 minutes.",
      es: "Por favor, esté listo en el punto de recogida en 30 minutos.",
      fr: "Veuillez être prêt au point de ramassage dans 30 minutes.",
      ar: "يرجى الاستعداد في نقطة الالتقاط خلال 30 دقيقة.",
      ps: "مهرباني وکړئ د 30 دقیقو په جریان کې د پورته کولو په نقطه کې چمتو اوسئ.",
      pt: "Por favor, esteja pronto no ponto de embarque em 30 minutos.",
      uk: "Будь ласка, будьте готові на пункті посадки через 30 хвилин.",
      ha: "Da fatan za a kasance a wurin ɗauka cikin mintuna 30.",
      ka: "გთხოვთ, 30 წუთში იყოთ მზად აეროპორტში მისასვლელ პუნქტზე.",
      ge: "გთხოვთ, 30 წუთში მზად იყავით აღების პუნქტში.",
    },
    type: "info",
  },
  {
    id: 2,
    icon: "/svg/successNotification.svg",
    title: {
      en: "Your booking was successful.",
      es: "Su reserva se realizó con éxito.",
      fr: "Votre réservation a été confirmée avec succès.",
      ar: "تم حجزك بنجاح.",
      ps: "ستاسې بکینګ بریالی و.",
      pt: "Sua reserva foi bem-sucedida.",
      uk: "Ваше бронювання пройшло успішно.",
      ha: "An yi nasarar yin ajiyar ku.",
      ka: "თქვენი დაჯავშნა წარმატებით შესრულდა.",
      ge: "თქვენი დაჯავშნა წარმატებით დასრულდა.",
    },

    type: "info",
  },
  {
    id: 3,
    icon: "/svg/yellowInfo.svg",
    title: {
      en: "Your bus departs at 10:00 AM.",
      es: "Su autobús sale a las 10:00 AM.",
      fr: "Votre bus part à 10h00.",
      ar: "حافلتك تغادر الساعة 10:00 صباحًا",
      ps: "ستاسې بس د 10:00 بجو پرانستل کېږي.",
      pt: "Seu ônibus parte às 10:00.",
      uk: "Ваш автобус відправляється о 10:00.",
      ha: "Baburinka zai tashi a 10:00 na safe.",
      ka: "თქვენი ავტობუსი გავა 10:00 საათზე.",
      ge: "თქვენი ავტობუსი გადის 10:00 საათზე.",
    },
    description: {
      en: "Please be ready at the pickup point in 30 minutes.",
      es: "Por favor, esté listo en el punto de recogida en 30 minutos.",
      fr: "Veuillez être prêt au point de ramassage dans 30 minutes.",
      ar: "يرجى الاستعداد في نقطة الالتقاط خلال 30 دقيقة.",
      ps: "مهرباني وکړئ د 30 دقیقو په جریان کې د پورته کولو په نقطه کې چمتو اوسئ.",
      pt: "Por favor, esteja pronto no ponto de embarque em 30 minutos.",
      uk: "Будь ласка, будьте готові на пункті посадки через 30 хвилин.",
      ha: "Da fatan za a kasance a wurin ɗauka cikin mintuna 30.",
      ka: "გთხოვთ, 30 წუთში იყოთ მზად აეროპორტში მისასვლელ პუნქტზე.",
      ge: "გთხოვთ, 30 წუთში მზად იყავით აღების პუნქტში.",
    },
    type: "success",
  },
  {
    id: 4,
    icon: "/svg/redInfo.svg",
    title: {
      en: "Your bus is running 30 minutes behind schedule.",
      es: "Tu cita es mañana a las 11:00 AM.",
      fr: "Votre rendez-vous est demain à 11h00.",
      ar: "حافلتك متأخرة بمقدار 30 دقيقة عن الموعد المحدد.",
      ps: "ستاسې بس د مهالویش څخه 30 دقیقې وروسته روان دی.",
      pt: "Seu ônibus está atrasado em 30 minutos.",
      uk: "Ваш автобус відстає на 30 хвилин від розкладу.",
      ha: "Baburinka yana tafiya minti 30 bayan jadawalin.",
      ka: "თქვენი ავტობუსი დაგვიანებულია 30 წუთით.",
      ge: "თქვენი ავტობუსი დაგვიანებულია 30 წუთით.",
    },
    description: {
      en: "You can choose another bus or continue this trip. Thank you for your patience!",
      es: "Puede elegir otro autobús o continuar con este viaje. ¡Gracias por su paciencia!",
      fr: "Vous pouvez choisir un autre bus ou continuer ce trajet. Merci pour votre patience !",
      ar: "يمكنك اختيار حافلة أخرى أو متابعة هذه الرحلة. شكرًا لصبرك!",
      ps: "تاسو کولی شئ بله بس غوره کړئ یا دا سفر ته دوام ورکړئ. ستاسو د صبر څخه مننه!",
      pt: "Você pode escolher outro ônibus ou continuar esta viagem. Obrigado pela sua paciência!",
      uk: "Ви можете обрати інший автобус або продовжити цю поїздку. Дякуємо за ваше терпіння!",
      ha: "Kuna iya zaɓar wani babur ko ci gaba da wannan tafiya. Na gode da haƙuri!",
      ka: "თქვენ შეგიძლიათ აირჩიოთ სხვა ავტობუსი ან გააგრძელოთ ეს მგზავრობა. გმადლობთ მოთმინებისთვის!",
      ge: "თქვენ შეგიძლიათ აირჩიოთ სხვა ავტობუსი ან გააგრძელოთ ეს მგზავრობა. გმადლობთ მოთმინებისთვის!",
    },
    type: "info",
  },
];

export const activityTabs = (t) => [
  { label: t("activity.activityTabs.booking"), value: "booking" },
  { label: t("activity.activityTabs.requests"), value: "maintenance" },
  { label: t("activity.activityTabs.incident"), value: "incident" },
];

export const activitiesFeedData = (t) => ({
  title: t("activity.activitycard.requestHeading"),
  actions: [
    {
      label: t("common.edit"),
      value: "edit",
    },
    {
      label: t("common.approveRequest"),
      value: "approve",
      style: { color: "#00B383", fontWeight: 600 },
    },
    {
      label: t("common.rejectRequest"),
      value: "reject",
      style: { color: "#F86969", fontWeight: 600 },
    },
  ],
  status: "approved",
  items: [
    {
      heading: t("activity.activitycard.dateTime"),
      content: {
        ar: "17 نوفمبر 2024، 09:30 ص",
        es: "17 de noviembre de 2024, 09:30 AM",
        fr: "17 novembre 2024, 09h30",
        ps: "17 نومبر 2024، 09:30 سهار",
        pt: "17 de novembro de 2024, 09:30",
        uk: "17 листопада 2024 р., 09:30",
        ha: "17 Nuwamba 2024, 09:30 Safiya",
        ka: "17 ნოემბერი, 2024, 09:30 სთ",
        en: "November 17, 2024, 09:30 AM",
      },
    },
    {
      heading: t("activity.activitycard.resident"),
      content: {
        ar: "سارة سميث (البيت #24)",
        es: "Sarah Smith (Casa #24)",
        fr: "Sarah Smith (Maison #24)",
        ps: "سارا سمیت (کور #24)",
        pt: "Sarah Smith (Casa #24)",
        uk: "Сара Сміт (Будинок #24)",
        ha: "Sarah Smith (Gida #24)",
        ka: "Sarah Smith (სახლი #24)",
        en: "Sarah Smith (House #24)",
      },
    },
    {
      heading: t("activity.activitycard.purpose"),
      content: {
        ar: "نظام التدفئة لا يعمل في غرفة المعيشة.",
        es: "El sistema de calefacción no funciona en la sala de estar.",
        fr: "Le système de chauffage ne fonctionne pas dans le salon.",
        ps: "د اوسپنې سیسټم په د استوګنې خونه کې کار نه کوي.",
        pt: "O sistema de aquecimento não está funcionando na sala de estar.",
        uk: "Система опалення не працює у вітальні.",
        ha: "Tsarin dumama baya aiki a ɗakin zama.",
        ka: "თბო სისტემა სარეცხის ოთახში არ მუშაობს.",
        en: "Heating system not working in the living room.",
      },
    },
    {
      heading: t("activity.activitycard.appointment"),
      content: {
        ar: "18 نوفمبر 2024، 2:00 م",
        es: "18 de noviembre de 2024, 2:00 PM",
        fr: "18 novembre 2024, 14h00",
        ps: "18 نومبر 2024، 2:00 ماسپښین",
        pt: "18 de novembro de 2024, 14:00",
        uk: "18 листопада 2024 р., 14:00",
        ha: "18 Nuwamba 2024, 2:00 Yamma",
        ka: "18 ნოემბერი 2024, 14:00 სთ",
        en: "November 18, 2024, 2:00 PM",
      },
    },
  ],
});

export const chartData = (t) => ({
  title: t("chart.residentTitle"),
});
