// export const FoodTokensData = [
//   {
//     id: 1,
//     residentName: "Alex Doe",
//     roomNo: "4567",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "4567",
//   },
//   {
//     id: 2,
//     residentName: "John Doe",
//     roomNo: "1234",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "1234",
//   },
//   {
//     id: 3,
//     residentName: "Alex Doe",
//     roomNo: "9012",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "9012",
//   },
//   {
//     id: 4,
//     residentName: "John Doe",
//     roomNo: "6789",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "6789",
//   },
//   {
//     id: 5,
//     residentName: "Anna Smith",
//     roomNo: "2345",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "2345",
//   },
//   {
//     id: 6,
//     residentName: "Alex Smith",
//     roomNo: "7890",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "7890",
//   },
//   {
//     id: 7,
//     residentName: "Michael Backer",
//     roomNo: "3456",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "3456",
//   },
//   {
//     id: 8,
//     residentName: "Lilia Stefanova",
//     roomNo: "8901",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "8901",
//   },
//   {
//     id: 9,
//     residentName: "Michael Backer",
//     roomNo: "4567",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "4567",
//   },
//   {
//     id: 10,
//     residentName: "Lilia Stefanova",
//     roomNo: "1234",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "1234",
//   },
//   {
//     id: 11,
//     residentName: "Michael Backer",
//     roomNo: "9012",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "9012",
//   },
//   {
//     id: 12,
//     residentName: "Lilia Stefanova",
//     roomNo: "6789",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "6789",
//   },
//   {
//     id: 13,
//     residentName: "Michael Backer",
//     roomNo: "2345",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     availableToken: "2345",
//   },
// ];
