// export const IncidentReportsData = [
//   {
//     id: 1,
//     incidentId: "IR001",
//     title: "Fall in hallway",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Calvin Horne",
//     reportedBy: "Kamila Cabrera",
//     location: "Block A",
//     severity: "High",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Resolved",
//     completedDate: "2023-08-09",
//   },
//   {
//     id: 2,
//     incidentId: "IR002",
//     title: "Loud noise complaint",
//     description: "Noise disturbance after midnight",
//     reportedInvoiced: "Ava Orr",
//     reportedBy: "Kaia Livingstone",
//     location: "Block A",
//     severity: "Low",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Under Review",
//     completedDate: "-",
//   },
//   {
//     id: 3,
//     incidentId: "MT001",
//     title: "Missing credit",
//     description: "Resident reported credits for missing area",
//     reportedInvoiced: "Jose Michael",
//     reportedBy: "Joseph Torrino",
//     location: "Block A",
//     severity: "Medium",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Resolved",
//     completedDate: "-",
//   },
//   {
//     id: 4,
//     incidentId: "MT001",
//     title: "Failing AC Unit",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Terence Martin",
//     reportedBy: "Craig Brook",
//     location: "Block A",
//     severity: "High",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Escalated",
//     completedDate: "-",
//   },
//   {
//     id: 5,
//     incidentId: "MT001",
//     title: "Stove Not Igniting",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Jada Barr",
//     reportedBy: "Sky York",
//     location: "Block A",
//     severity: "Low",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Resolved",
//     completedDate: "-",
//   },
//   {
//     id: 6,
//     incidentId: "MT001",
//     title: "Dryer Vent Issue",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Claudia Grimes",
//     reportedBy: "Meadow Torres",
//     location: "Block A",
//     severity: "Medium",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Pending",
//     completedDate: "-",
//   },
//   {
//     id: 7,
//     incidentId: "MT001",
//     title: "Showerhead Leak",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Alyssa Boyle",
//     reportedBy: "Lennon Vales",
//     location: "Block A",
//     severity: "High",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Resolved",
//     completedDate: "-",
//   },
//   {
//     id: 8,
//     incidentId: "MT001",
//     title: "HVAC System Failure",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Alisha Pace",
//     reportedBy: "Raven Pate",
//     location: "Block A",
//     severity: "Low",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Escalated",
//     completedDate: "-",
//   },
//   {
//     id: 9,
//     incidentId: "MT001",
//     title: "Sliding Door Stuck",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Julien Hines",
//     reportedBy: "Tomas Blair",
//     location: "Block A",
//     severity: "Medium",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Escalated",
//     completedDate: "-",
//   },
//   {
//     id: 10,
//     incidentId: "MT001",
//     title: "Cracked Sidewalk",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Millie Frye",
//     reportedBy: "Avery Corner",
//     location: "Block A",
//     severity: "High",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Under Review",
//     completedDate: "-",
//   },
//   {
//     id: 11,
//     incidentId: "MT001",
//     title: "Broken Sprinkler",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Eric Bowman",
//     reportedBy: "Brock Rosa",
//     location: "Block A",
//     severity: "Low",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Resolved",
//     completedDate: "-",
//   },
//   {
//     id: 12,
//     incidentId: "MT001",
//     title: "Gutter Overflow",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Kailyn Acosta",
//     reportedBy: "Akash Myers",
//     location: "Block A",
//     severity: "Medium",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Escalated",
//     completedDate: "-",
//   },
//   {
//     id: 13,
//     incidentId: "MT001",
//     title: "Blocked Fire Exit",
//     description: "Resident slipped in corridor near A-6...",
//     reportedInvoiced: "Landen Holman",
//     reportedBy: "Viviana Brooks",
//     location: "Block A",
//     severity: "High",
//     dateTime: "2023-08-05 • 10:15AM",
//     status: "Resolved",
//     completedDate: "-",
//   },
// ];
