// export const MaintenanceRequestsData = [
//   {
//     id: 1,
//     residentName: "Briana Coleman",
//     roomNumber: "456",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Heating Issues",
//     shortDescription: "Issues with heating systems...",
//     status: "Low",
//   },
//   {
//     id: 2,
//     residentName: "Cody Cotton",
//     roomNumber: "789",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Electrical Problems",
//     shortDescription: "Problems with electrical syst...",
//     status: "Urgent",
//   },
//   {
//     id: 3,
//     residentName: "Joey Harrison",
//     roomNumber: "321",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Water Leakage",
//     shortDescription: "Water leaking from pipes or...",
//     status: "Medium",
//   },
//   {
//     id: 4,
//     residentName: "Zoe Little",
//     roomNumber: "654",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Repairs",
//     shortDescription: "Repairs needed for gas lines...",
//     status: "Urgent",
//   },
//   {
//     id: 5,
//     residentName: "Amiya Boyd",
//     roomNumber: "987",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "HVAC Maintenance",
//     shortDescription: "Regular maintenance require...",
//     status: "Low",
//   },
//   {
//     id: 6,
//     residentName: "Lilith Thompson",
//     roomNumber: "234",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Pipe Blockage",
//     shortDescription: "Blocked pipes causing slow d...",
//     status: "Medium",
//   },
//   {
//     id: 7,
//     residentName: "Devan Bauer",
//     roomNumber: "876",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Drainage Issues",
//     shortDescription: "Problems with drainage syste...",
//     status: "Low",
//   },
//   {
//     id: 8,
//     residentName: "Leia Armstrong",
//     roomNumber: "543",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Sewer Backup",
//     shortDescription: "Sewage backup causing sanit...",
//     status: "Medium",
//   },
//   {
//     id: 9,
//     residentName: "Sky Palmer",
//     roomNumber: "210",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Thermostat Malfunction",
//     shortDescription: "Malfunctioning thermostat a...",
//     status: "Urgent",
//   },
//   {
//     id: 10,
//     residentName: "Joslyn Morrison",
//     roomNumber: "135",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Faucet Repairs",
//     shortDescription: "Repairs needed for faucets t...",
//     status: "Low",
//   },
//   {
//     id: 11,
//     residentName: "Ivan Short",
//     roomNumber: "246",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Toilet Clogs",
//     shortDescription: "Clogs in toilets causing incon...",
//     status: "Medium",
//   },
//   {
//     id: 12,
//     residentName: "Arianna Ross",
//     roomNumber: "357",
//     requestDateTime: "2025-08-05 • 10:15AM",
//     issueCategory: "Water Heater Issues",
//     shortDescription: "Issues with water heaters aff...",
//     status: "Medium",
//   },
// ];
