// export const ManageItemsData = [
//   {
//     id: 1,
//     photo: "/dev-images/dummyFood.jpg",
//     shippingOptions: "Pick Up & Delivery",
//     itemName: "Apple Pie",
//     stock: 52,
//     points: 45,
//     dateAdded: "11-09-2023",
//     category: "Bakery",
//   },
//   {
//     id: 2,
//     photo: "/dev-images/dummyFood.jpg",
//     shippingOptions: "Pick Up",
//     itemName: "Banana Bread",
//     stock: 28,
//     points: 67,
//     dateAdded: "11-09-2023",
//     category: "Bakery",
//   },
//   {
//     id: 3,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Carrot Cake",
//     shippingOptions: "Delivery",
//     stock: 37,
//     points: 29,
//     dateAdded: "11-09-2023",
//     category: "Bakery",
//   },
//   {
//     id: 4,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Doughnut",
//     shippingOptions: "Pick Up & Delivery",
//     stock: 50,
//     points: 82,
//     dateAdded: "11-09-2023",
//     category: "Bakery",
//   },
//   {
//     id: 5,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Egg Salad",
//     shippingOptions: "Pick Up",
//     stock: 41,
//     points: 54,
//     dateAdded: "11-09-2023",
//     category: "Salads",
//   },
//   {
//     id: 6,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Fruit Tart",
//     shippingOptions: "Delivery",
//     stock: 29,
//     points: 38,
//     dateAdded: "11-09-2023",
//     category: "Desserts",
//   },
//   {
//     id: 7,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Ginger Cookies",
//     shippingOptions: "Pick Up & Delivery",
//     stock: 34,
//     points: 91,
//     dateAdded: "11-09-2023",
//     category: "Bakery",
//   },
//   {
//     id: 8,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Honey Glazed Ham",
//     shippingOptions: "Pick Up",
//     stock: 46,
//     points: 73,
//     dateAdded: "11-09-2023",
//     category: "Meat",
//   },
//   {
//     id: 9,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Ice Cream Sundae",
//     shippingOptions: "Delivery",
//     stock: 39,
//     points: 12,
//     dateAdded: "11-09-2023",
//     category: "Desserts",
//   },
//   {
//     id: 10,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Jelly Beans",
//     shippingOptions: "Pick Up & Delivery",
//     stock: 27,
//     points: 60,
//     dateAdded: "11-09-2023",
//     category: "Snacks",
//   },
//   {
//     id: 11,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Kale Salad",
//     shippingOptions: "Pick Up",
//     stock: 35,
//     points: 47,
//     dateAdded: "11-09-2023",
//     category: "Salads",
//   },
//   {
//     id: 12,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Lemon Meringue Pie",
//     shippingOptions: "Delivery",
//     stock: 44,
//     points: 33,
//     dateAdded: "11-09-2023",
//     category: "Desserts",
//   },
//   {
//     id: 13,
//     photo: "/dev-images/dummyFood.jpg",
//     itemName: "Mango Sorbet",
//     shippingOptions: "Pick Up & Delivery",
//     stock: 30,
//     points: 76,
//     dateAdded: "11-09-2023",
//     category: "Desserts",
//   },
// ];
