// export const RoomsHousesData = [
//   {
//     id: 1,
//     houseRoomNumber: "A-101",
//     numberOfBeds: 2,
//     type: {
//       en: "House",
//       es: "Máquina A",
//       fr: "Machine A",
//     },
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 2,
//     houseRoomNumber: "B-205",
//     numberOfBeds: 1,
//     type: "Room",
//     occupancyStatus: "vacant",
//   },
//   {
//     id: 3,
//     houseRoomNumber: "C-304",
//     numberOfBeds: 3,
//     type: "Apartment",
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 4,
//     houseRoomNumber: "A-112",
//     numberOfBeds: 2,
//     type: "House",
//     occupancyStatus: "vacant",
//   },
//   {
//     id: 5,
//     houseRoomNumber: "B-156",
//     numberOfBeds: 1,
//     type: "Room",
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 6,
//     houseRoomNumber: "C-278",
//     numberOfBeds: 4,
//     type: "Apartment",
//     occupancyStatus: "vacant",
//   },
//   {
//     id: 7,
//     houseRoomNumber: "A-203",
//     numberOfBeds: 2,
//     type: "House",
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 8,
//     houseRoomNumber: "B-341",
//     numberOfBeds: 1,
//     type: "Room",
//     occupancyStatus: "maintenance",
//   },
//   {
//     id: 9,
//     houseRoomNumber: "C-145",
//     numberOfBeds: 3,
//     type: "Apartment",
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 10,
//     houseRoomNumber: "A-087",
//     numberOfBeds: 2,
//     type: "House",
//     occupancyStatus: "vacant",
//   },
//   {
//     id: 11,
//     houseRoomNumber: "B-298",
//     numberOfBeds: 1,
//     type: "Room",
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 12,
//     houseRoomNumber: "C-432",
//     numberOfBeds: 4,
//     type: "Apartment",
//     occupancyStatus: "vacant",
//   },
//   {
//     id: 13,
//     houseRoomNumber: "A-156",
//     numberOfBeds: 2,
//     type: "House",
//     occupancyStatus: "occupied",
//   },
//   {
//     id: 14,
//     houseRoomNumber: "B-123",
//     numberOfBeds: 1,
//     type: "Room",
//     occupancyStatus: "maintenance",
//   },
//   {
//     id: 15,
//     houseRoomNumber: "C-067",
//     numberOfBeds: 3,
//     type: "Apartment",
//     occupancyStatus: "vacant",
//   },
// ];
