// export const staffsData = [
//   {
//     staffId: "ST001",
//     name: "Myla Willis",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Active",
//   },
//   {
//     staffId: "ST002",
//     name: "Kali Burch",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
//   {
//     staffId: "ST003",
//     name: "Phoenix Spence",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
//   {
//     staffId: "ST004",
//     name: "Kyra Rodriguez",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Active",
//   },
//   {
//     staffId: "ST005",
//     name: "Frances Wong",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
//   {
//     staffId: "ST006",
//     name: "Chase Sanchez",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Active",
//   },
//   {
//     staffId: "ST007",
//     name: "Frances Vasquez",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
//   {
//     staffId: "ST008",
//     name: "Randy Levine",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Active",
//   },
//   {
//     staffId: "ST009",
//     name: "Adam Chang",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
//   {
//     staffId: "ST010",
//     name: "Bianca Lowery",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Active",
//   },
//   {
//     staffId: "ST011",
//     name: "Faith Holman",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
//   {
//     staffId: "ST012",
//     name: "Kyson Meadows",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Active",
//   },
//   {
//     staffId: "ST013",
//     name: "Emmaline Cooke",
//     email: "example@gmail.com",
//     countryCode: "+1",
//     phoneNumber: "8005550101",
//     status: "Deactivate",
//   },
// ];
