// export const visitorBookingTableData = [
//   {
//     _id: "1",
//     residentName: "John Doe",
//     visitorName: "Emily Doe",
//     relationShipToResident: "Wife",
//     status: "Pending",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "2",
//     residentName: "Jane Smith",
//     visitorName: "Michael Smith",
//     relationShipToResident: "Brother",
//     status: "Completed",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "3",
//     residentName: "Alice Johnson",
//     visitorName: "Sarah Johnson",
//     relationShipToResident: "Mother",
//     status: "In Progress",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "4",
//     residentName: "Bob Brown",
//     visitorName: "Tom Brown",
//     relationShipToResident: "Father",
//     status: "Pending",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "5",
//     residentName: "Charlie Davis",
//     visitorName: "Anna Davis",
//     relationShipToResident: "Sister",
//     status: "Pending",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "6",
//     residentName: "David Wilson",
//     visitorName: "Peter Wilson",
//     relationShipToResident: "Friend",
//     status: "Completed",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "7",
//     residentName: "Emma Thompson",
//     visitorName: "Olivia Thompson",
//     relationShipToResident: "Daughter",
//     status: "In Progress",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "8",
//     residentName: "Frank Harris",
//     visitorName: "Sam Harris",
//     relationShipToResident: "Son",
//     status: "In Progress",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "9",
//     residentName: "Grace Lee",
//     visitorName: "Lucy Lee",
//     relationShipToResident: "Mother",
//     status: "In Progress",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
//   {
//     _id: "10",
//     residentName: "Henry Adams",
//     visitorName: "Jack Adams",
//     relationShipToResident: "Friend",
//     status: "In Progress",
//     dateAndTime: "2023-10-01 10:00 AM",
//   },
// ];
