export const PERMISSIONS = {
  DASHBOARD: {
    VIEW_DASHBOARD: "view-dashboard",
  },
  STAFF: {
    VIEW_STAFF: "view-staff",
    ADD_EDIT_STAFF: "add-edit-staff",
  },
  POSITIONS: {
    VIEW_POSITIONS: "view-positions",
    ADD_EDIT_POSITION: "add-edit-position",
  },
  ACCOMMODATION: {
    VIEW_ACCOMMODATIONS: "view-accommodations",
    ADD_EDIT_ACCOMMODATION: "add-edit-accommodation",
    // UPDATE_ACCOMMODATION_BOOKING_STATUS: "update-accommodation-booking-status",
  },
  RESIDENT: {
    VIEW_RESIDENTS: "view-residents",
    ADD_EDIT_RESIDENT: "add-edit-resident",
  },
  FOOD_TOKENS: {
    VIEW_FOOD_TOKENS: "view-food-tokens",
    ADD_FOOD_TOKEN: "add-food-token",
  },
  INCIDENT_REPORT: {
    VIEW_INCIDENT_REPORTS: "view-incident-reports",
    ADD_INCIDENT_REPORT: "add-incident-report",
    // APPROVE_REJECT_MAINTENANCE_REQUEST: "approve-reject-maintenance-request",
  },
  MANAGE_PRODUCTS: {
    VIEW_PRODUCTS: "view-products",
    ADD_EDIT_PRODUCT: "add-edit-product",
    VIEW_PRODUCT_CATEGORIES: "view-product-categories",
    ADD_EDIT_PRODUCT_CATEGORY: "add-edit-product-category",
  },
  REPORT_ANALYTICS: {
    VIEW_REPORTS_AND_ANALYTICS: "view-reports-and-analytics",
  },

  MAINTENANCE_CATEGORIES: {
    VIEW_MAINTENANCE_REQUEST_CATEGORIES: "view-maintenance-request-categories",
    ADD_EDIT_MAINTENANCE_REQUEST_CATEGORY:
      "add-edit-maintenance-request-category",
  },
  MACHINES: {
    VIEW_MACHINES: "view-machines",
    ADD_EDIT_MACHINE: "add-edit-machine",
  },
  FAQS: {
    VIEW_FAQS: "view-faqs",
    ADD_EDIT_FAQ: "add-edit-faq",
  },

  HELPLINE: {
    VIEW_HELPLINES: "view-help-lines",
    ADD_EDIT_HELPLINE: "add-edit-help-line",
  },
  LAUNDRY_BOOKINGS: {
    VIEW_LAUNDRY_BOOKINGS: "view-laundry-bookings",
    UPDATE_LAUNDRY_BOOKING_STATUS: "update-laundry-booking-status",
  },
  BUS_BOOKINGS: {
    VIEW_BUS_BOOKINGS: "view-bus-bookings",
    ADD_EDIT_BUS_BOOKINGS: "add-edit-bus-bookings",
  },
  STAFF_BOOKINGS: {
    VIEW_STAFF_BOOKINGS: "view-staff-bookings",
    UPDATE_STAFF_BOOKING_STATUS: "update-staff-booking-status",
  },
  VISITOR_BOOKINGS: {
    VIEW_VISITOR_BOOKINGS: "view-visitor-bookings",
    UPDATE_VISITOR_BOOKING_STATUS: "update-visitor-booking-status",
  },
  MAINTENANCE_REQUEST: {
    VIEW_MAINTENANCE_REQUESTS: "view-maintenance-requests",
    APPROVE_REJECT_MAINTENANCE_REQUEST: "approve-reject-maintenance-request",
  },
  BUS: {
    VIEW_BUSES: "view-buses",
    ADD_EDIT_BUS: "add-edit-bus",
  },
  DOCUMENT_CENTER: {
    VIEW_DOCUMENTS: "view-documents",
    ADD_EDIT_DOCUMENT: "add-edit-document",
  },
  ORDERS: {
    VIEW_ORDERS: "view-orders",
    EDIT_ORDER: "edit-order",
  },

  NOTIFICATIONS: {
    VIEW_NOTIFICATIONS: "view-notifications",
  },
  APP_CONFIGS: {
    VIEW_APP_CONFIGS: "view-app-configs",
    EDIT_APP_CONFIGS: "edit-app-configs",
  },
  APPOINTMENTS_SLOTS: {
    VIEW_STAFF_APPOINTMENTS: "view-staff",
    SEE_APPOINTMENTS_SLOTS: "see-appointments-slots",
  },
  LAUNDRY_SLOTS: {
    VIEW_MACHINE_CATEGORIES: "view-machines",
    SEE_LAUNDRY_SLOTS: "see-laundry-slots",
  },
  VISITOR_SLOTS: {
    VIEW_ROOMS: "view-accommodations",
    SEE_SLOTS: "see-visitor-slots",
  },
  CMS: {
    VIEW_CMS: "view-cms",
    EDIT_CMS: "edit-cms",
  },
};
export const permissionGroups = {
  "food-token-add-assign": ["add-food-token", "view-residents"],

  "incident-add-assign": [
    "add-incident-report",
    "view-residents",
    "view-staff",
  ],

  "product-view-all": ["view-products", "view-product-categories"],

  "product-edit-all": ["add-edit-product", "add-edit-product-category"],

  "see-appointments-slots": ["view-staff", "see-appointments-slots"],

  "see-laundry-slots": ["view-machines", "see-laundry-slots"],
  "see-visitor-slots": ["view-accommodations", "see-visitor-slots"],
};

// Permission groups for easier management
export const PERMISSION_GROUPS = {
  DASHBOARD: [PERMISSIONS.DASHBOARD.VIEW_DASHBOARD],

  STAFF: [
    PERMISSIONS.STAFF.VIEW_STAFF,
    PERMISSIONS.STAFF.ADD_EDIT_STAFF,
    PERMISSIONS.POSITIONS.VIEW_POSITIONS,
  ],

  POSITIONS: [
    PERMISSIONS.POSITIONS.VIEW_POSITIONS,
    PERMISSIONS.POSITIONS.ADD_EDIT_POSITION,
  ],

  ACCOMMODATION: [
    PERMISSIONS.ACCOMMODATION.VIEW_ACCOMMODATIONS,
    PERMISSIONS.ACCOMMODATION.ADD_EDIT_ACCOMMODATION,
    // PERMISSIONS.ACCOMMODATION.UPDATE_ACCOMMODATION_BOOKING_STATUS,
  ],

  RESIDENT: [
    PERMISSIONS.RESIDENT.VIEW_RESIDENTS,
    PERMISSIONS.RESIDENT.ADD_EDIT_RESIDENT,
  ],

  FOOD_TOKENS: [
    PERMISSIONS.FOOD_TOKENS.VIEW_FOOD_TOKENS,
    PERMISSIONS.FOOD_TOKENS.ADD_FOOD_TOKEN,
    PERMISSIONS.RESIDENT.VIEW_RESIDENTS,
  ],

  INCIDENT_REPORT: [
    PERMISSIONS.INCIDENT_REPORT.VIEW_INCIDENT_REPORTS,
    PERMISSIONS.INCIDENT_REPORT.ADD_INCIDENT_REPORT,
    // PERMISSIONS.INCIDENT_REPORT.APPROVE_REJECT_MAINTENANCE_REQUEST,
    PERMISSIONS.RESIDENT.VIEW_RESIDENTS,
    PERMISSIONS.STAFF.VIEW_STAFF,
  ],

  MANAGE_PRODUCTS: [
    PERMISSIONS.MANAGE_PRODUCTS.VIEW_PRODUCTS,
    PERMISSIONS.MANAGE_PRODUCTS.ADD_EDIT_PRODUCT,
    PERMISSIONS.MANAGE_PRODUCTS.VIEW_PRODUCT_CATEGORIES,
    PERMISSIONS.MANAGE_PRODUCTS.ADD_EDIT_PRODUCT_CATEGORY,
  ],

  REPORT_ANALYTICS: [PERMISSIONS.REPORT_ANALYTICS.VIEW_REPORTS_AND_ANALYTICS],

  MAINTENANCE_CATEGORIES: [
    PERMISSIONS.MAINTENANCE_CATEGORIES.VIEW_MAINTENANCE_REQUEST_CATEGORIES,
    PERMISSIONS.MAINTENANCE_CATEGORIES.ADD_EDIT_MAINTENANCE_REQUEST_CATEGORY,
  ],

  MACHINES: [
    PERMISSIONS.MACHINES.VIEW_MACHINES,
    PERMISSIONS.MACHINES.ADD_EDIT_MACHINE,
  ],

  FAQS: [PERMISSIONS.FAQS.VIEW_FAQS, PERMISSIONS.FAQS.ADD_EDIT_FAQ],
  HELPLINE: [
    PERMISSIONS.HELPLINE.VIEW_HELPLINES,
    PERMISSIONS.HELPLINE.ADD_EDIT_HELPLINE,
  ],

  LAUNDRY_BOOKINGS: [
    PERMISSIONS.LAUNDRY_BOOKINGS.VIEW_LAUNDRY_BOOKINGS,
    PERMISSIONS.LAUNDRY_BOOKINGS.UPDATE_LAUNDRY_BOOKING_STATUS,
  ],

  BUS_BOOKINGS: [
    PERMISSIONS.BUS_BOOKINGS.VIEW_BUS_BOOKINGS,
    PERMISSIONS.BUS_BOOKINGS.ADD_EDIT_BUS_BOOKINGS,
  ],

  STAFF_BOOKINGS: [
    PERMISSIONS.STAFF_BOOKINGS.VIEW_STAFF_BOOKINGS,
    PERMISSIONS.STAFF_BOOKINGS.UPDATE_STAFF_BOOKING_STATUS,
  ],

  VISITOR_BOOKINGS: [
    PERMISSIONS.VISITOR_BOOKINGS.VIEW_VISITOR_BOOKINGS,
    PERMISSIONS.VISITOR_BOOKINGS.UPDATE_VISITOR_BOOKING_STATUS,
  ],

  MAINTENANCE_REQUEST: [
    PERMISSIONS.MAINTENANCE_REQUEST.VIEW_MAINTENANCE_REQUESTS,
    PERMISSIONS.MAINTENANCE_REQUEST.APPROVE_REJECT_MAINTENANCE_REQUEST,
  ],

  BUS: [PERMISSIONS.BUS.VIEW_BUSES, PERMISSIONS.BUS.ADD_EDIT_BUS],

  DOCUMENT_CENTER: [
    PERMISSIONS.DOCUMENT_CENTER.VIEW_DOCUMENTS,
    PERMISSIONS.DOCUMENT_CENTER.ADD_EDIT_DOCUMENT,
  ],

  ORDERS: [PERMISSIONS.ORDERS.VIEW_ORDERS, PERMISSIONS.ORDERS.EDIT_ORDER],

  NOTIFICATIONS: [PERMISSIONS.NOTIFICATIONS.VIEW_NOTIFICATIONS],

  APP_CONFIGS: [
    PERMISSIONS.APP_CONFIGS.VIEW_APP_CONFIGS,
    PERMISSIONS.APP_CONFIGS.EDIT_APP_CONFIGS,
  ],

  // Grouped categories
  TIME_SLOTS: [
    PERMISSIONS.APPOINTMENTS_SLOTS.VIEW_APPOINTMENTS_SLOTS,
    PERMISSIONS.APPOINTMENTS_SLOTS.VIEW_STAFF_APPOINTMENTS,
    PERMISSIONS.LAUNDRY_SLOTS.VIEW_MACHINE_CATEGORIES,
    PERMISSIONS.LAUNDRY_SLOTS.VIEW_LAUNDRY_SLOTS,
    PERMISSIONS.VISITOR_SLOTS.VIEW_ROOMS,
    PERMISSIONS.VISITOR_SLOTS.SEE_SLOTS,
  ],

  CRUD: [
    ...[
      PERMISSIONS.MAINTENANCE_CATEGORIES.VIEW_MAINTENANCE_REQUEST_CATEGORIES,
      PERMISSIONS.MAINTENANCE_CATEGORIES.ADD_EDIT_MAINTENANCE_REQUEST_CATEGORY,
    ],
    ...[
      PERMISSIONS.MACHINES.VIEW_MACHINES,
      PERMISSIONS.MACHINES.ADD_EDIT_MACHINE,
    ],
    ...[PERMISSIONS.FAQS.VIEW_FAQS, PERMISSIONS.FAQS.ADD_EDIT_FAQ],
    ...[
      PERMISSIONS.HELPLINE.VIEW_HELPLINES,
      PERMISSIONS.HELPLINE.ADD_EDIT_HELPLINE,
    ],
    ...[
      PERMISSIONS.POSITIONS.VIEW_POSITIONS,
      PERMISSIONS.POSITIONS.ADD_EDIT_POSITION,
    ],
  ],
  CMS: [PERMISSIONS.CMS.VIEW_CMS, PERMISSIONS.CMS.EDIT_CMS],
};

export const ROUTE_PERMISSIONS = {
  "/appointments": [...PERMISSION_GROUPS.STAFF_BOOKINGS],

  "/bus-booking": [...PERMISSION_GROUPS.BUS_BOOKINGS],
  "/bus-management": [...PERMISSION_GROUPS.BUS],

  "/dashboard": [...PERMISSION_GROUPS.DASHBOARD],

  "/faqs": [...PERMISSION_GROUPS.FAQS],

  "/food-tokens": [...PERMISSION_GROUPS.FOOD_TOKENS],

  "/incident-reports": [...PERMISSION_GROUPS.INCIDENT_REPORT],

  "/laundry-booking": [...PERMISSION_GROUPS.LAUNDRY_BOOKINGS],

  "/maintenance-requests": [...PERMISSION_GROUPS.MAINTENANCE_REQUEST],

  "/manage-items": [...PERMISSION_GROUPS.MANAGE_PRODUCTS],

  "/notifications": [...PERMISSION_GROUPS.NOTIFICATIONS],

  "/profile-settings": [],

  "/reports-analytics": [...PERMISSION_GROUPS.REPORT_ANALYTICS],

  "/residents": [...PERMISSION_GROUPS.RESIDENT],

  "/rooms-houses": [...PERMISSION_GROUPS.ACCOMMODATION],

  "/settings": [],

  "/staffs": [...PERMISSION_GROUPS.STAFF],

  "/time-slots": [...PERMISSION_GROUPS.TIME_SLOTS],
  "/time-slots/appointment-slots": [
    PERMISSIONS.APPOINTMENTS_SLOTS.VIEW_APPOINTMENTS_SLOTS,
    PERMISSIONS.APPOINTMENTS_SLOTS.VIEW_STAFF_APPOINTMENTS,
  ],
  "/time-slots/laundry-booking-slots": [
    PERMISSIONS.LAUNDRY_SLOTS.VIEW_LAUNDRY_SLOTS,
    PERMISSIONS.LAUNDRY_SLOTS.VIEW_MACHINE_CATEGORIES,
  ],
  "/time-slots/visitor-slots": [
    PERMISSIONS.VISITOR_SLOTS.VIEW_ROOMS,
    PERMISSIONS.VISITOR_SLOTS.SEE_SLOTS,
  ],

  "/visitor-booking": [...PERMISSION_GROUPS.VISITOR_BOOKINGS],

  "/crud": [...PERMISSION_GROUPS.CRUD],
  "/crud/crud-maintenance-categories": [
    ...PERMISSION_GROUPS.MAINTENANCE_CATEGORIES,
  ],
  "/crud/crud-machine": [...PERMISSION_GROUPS.MACHINES],
  "/crud/crud-faqs": [...PERMISSION_GROUPS.FAQS],
  "/crud/crud-helplines": [...PERMISSION_GROUPS.HELPLINE],
  "/crud/crud-positions": [...PERMISSION_GROUPS.POSITIONS],
  "/cms": [...PERMISSION_GROUPS.CMS],
};

export default PERMISSIONS;
