// src/locales/statusTranslations.js
export const statusTranslations = {
  en: {
    confirmed: "Confirmed",
    low: "Low",
    completed: "Completed",
    resolved: "Resolved",
    approved: "Approved",
    active: "Active",
    unoccupied: "Unoccupied",
    "on-site": "On-site",
    "off-site": "Off-site",
    open: "Open",
    "in-progress": "In-progress",
    accepted: "Accepted",
    delivery: "Delivery",
    escalated: "Escalated",
    urgent: "Urgent",
    "in progress": "In progress",
    inactive: "Inactive",
    rejected: "Rejected",
    pending: "Pending",
    "under review": "Under review",
    medium: "Medium",
    high: "High",
    maintenance: "Maintenance",
    occupied: "Occupied",
    "partially-occupied": "Partially Occupied",
    "under-review": "Under-review",
    pickup: "Pickup",
    "pickup-delivery": "Pickup & Delivery",
    house: "House",
    apartment: "Apartment",
    room: "Room",
    cancelled: "Cancelled",
  },
  pt: {
    confirmed: "Confirmado",
    low: "Baixo",
    completed: "Concluído",
    resolved: "Resolvido",
    approved: "Aprovado",
    active: "Ativo",
    unoccupied: "Desocupado",
    "on-site": "No local",
    "off-site": "Fora do local",
    open: "Aberto",
    "in-progress": "Em andamento",
    accepted: "Aceito",
    delivery: "Entrega",
    escalated: "Escalado",
    urgent: "Urgente",
    "in progress": "Em andamento",
    inactive: "Inativo",
    rejected: "Rejeitado",
    pending: "Pendente",
    "under review": "Em revisão",
    medium: "Médio",
    high: "Alto",
    maintenance: "Manutenção",
    occupied: "Ocupado",
    "partially-occupied": "Parcialmente Ocupado",
    "under-review": "Em revisão",
    pickup: "Recolha",
    "pickup-delivery": "Retirada e Entrega",
    house: "Casa",
    apartment: "Apartamento",
    room: "Quarto",
    cancelled: "Cancelado",
  },
  es: {
    confirmed: "Confirmado",
    low: "Bajo",
    completed: "Completado",
    resolved: "Resuelto",
    approved: "Aprobado",
    active: "Activo",
    unoccupied: "Desocupado",
    "on-site": "En el sitio",
    "off-site": "Fuera del sitio",
    open: "Abierto",
    "in-progress": "En progreso",
    accepted: "Aceptado",
    delivery: "Entrega",
    escalated: "Escalado",
    urgent: "Urgente",
    "in progress": "En progreso",
    inactive: "Inactivo",
    rejected: "Rechazado",
    pending: "Pendiente",
    "under review": "En revisión",
    medium: "Medio",
    high: "Alto",
    maintenance: "Mantenimiento",
    occupied: "Ocupado",
    "partially-occupied": "Parcialmente Ocupado",
    "under-review": "En revisión",
    pickup: "Recogida",
    "pickup-delivery": "Recogida y Entrega",
    house: "Casa",
    apartment: "Apartamento",
    room: "Habitación",
    cancelled: "Cancelado",
  },
  fr: {
    confirmed: "Confirmé",
    low: "Faible",
    completed: "Terminé",
    resolved: "Résolu",
    approved: "Approuvé",
    active: "Actif",
    unoccupied: "Inoccupé",
    "on-site": "Sur site",
    "off-site": "Hors site",
    open: "Ouvert",
    "in-progress": "En cours",
    accepted: "Accepté",
    delivery: "Livraison",
    escalated: "Escaladé",
    urgent: "Urgent",
    "in progress": "En cours",
    inactive: "Inactif",
    rejected: "Rejeté",
    pending: "En attente",
    "under review": "En révision",
    medium: "Moyen",
    high: "Élevé",
    maintenance: "Maintenance",
    occupied: "Occupé",
    "partially-occupied": "Partiellement Occupé",
    "under-review": "En révision",
    pickup: "Ramassage",
    "pickup-delivery": "Retrait et Livraison",
    house: "Maison",
    apartment: "Appartement",
    room: "Chambre",
    cancelled: "Annulé",
  },
  ka: {
    confirmed: "დადასტურებულია",
    low: "დაბალი",
    completed: "დასრულებულია",
    resolved: "ამოწურული",
    approved: "დამტკიცებულია",
    active: "აქტიური",
    unoccupied: "თავისუფალი",
    "on-site": "ადგილზე",
    "off-site": "გარეთ",
    open: "ღია",
    "in-progress": "მიმდინარეობს",
    accepted: "მიღებულია",
    delivery: "მიწოდება",
    escalated: "ესკალირებულია",
    urgent: "სასწრაფო",
    "in progress": "მიმდინარეობს",
    inactive: "არააქტიური",
    rejected: "უარყოფილია",
    pending: "მოლოდინში",
    "under review": "გადახედვის პროცესში",
    medium: "საშუალო",
    high: "მაღალი",
    maintenance: "მომსახურება",
    occupied: "დაკავებული",
    "partially-occupied": "ნაწილობრივ დაკავებული",
    "under-review": "გადახედვის პროცესში",
    pickup: "მიღება",
    "pickup-delivery": "ಪಿಕ್‌ಅಪ್ ಮತ್ತು ವಿತರಣಾ",
    house: "სახლი",
    apartment: "ბინა",
    room: "ოთახი",
    cancelled: "გაუქმებულია",
  },
  ha: {
    confirmed: "An tabbatar",
    low: "Ƙarami",
    completed: "An gama",
    resolved: "An warware",
    approved: "An amince",
    active: "Aiki",
    unoccupied: "Ba a mamaye ba",
    "on-site": "A wurin",
    "off-site": "Waje",
    open: "A buɗe",
    "in-progress": "Aiki yana gudana",
    accepted: "An karɓa",
    delivery: "Isarwa",
    escalated: "An ɗaga",
    urgent: "Gaggawa",
    "in progress": "Ana ci gaba",
    inactive: "Ba ya aiki",
    rejected: "An ƙi",
    pending: "Ana jiran",
    "under review": "Ana dubawa",
    medium: "Matsakaici",
    high: "Babba",
    maintenance: "Gyara",
    occupied: "An mamaye",
    "partially-occupied": "An mamaye wani bangare",
    "under-review": "Ana dubawa",
    pickup: "Dauka",
    "pickup-delivery": "Dauka da Isarw",
    house: "Gida",
    apartment: "Gini",
    room: "Daki",
    cancelled: "An soke",
  },
  ar: {
    confirmed: "مؤكد",
    low: "منخفض",
    completed: "مكتمل",
    resolved: "تم الحل",
    approved: "موافق عليه",
    active: "نشط",
    unoccupied: "شاغر",
    "on-site": "في الموقع",
    "off-site": "خارج الموقع",
    open: "مفتوح",
    "in-progress": "قيد التنفيذ",
    accepted: "مقبول",
    delivery: "توصيل",
    escalated: "تم التصعيد",
    urgent: "عاجل",
    "in progress": "قيد التقدم",
    inactive: "غير نشط",
    rejected: "مرفوض",
    pending: "قيد الانتظار",
    "under review": "قيد المراجعة",
    medium: "متوسط",
    high: "مرتفع",
    maintenance: "صيانة",
    occupied: "مشغول",
    "partially-occupied": "مشغول جزئياً",
    "under-review": "قيد المراجعة",
    pickup: "استلام",
    "pickup-delivery": "الاستلام والتوصيل",
    house: "منزل",
    apartment: "شقة",
    room: "غرفة",
    cancelled: "ألغيت",
  },
  uk: {
    confirmed: "Підтверджено",
    low: "Низький",
    completed: "Завершено",
    resolved: "Вирішено",
    approved: "Затверджено",
    active: "Активний",
    unoccupied: "Вільний",
    "on-site": "На місці",
    "off-site": "Поза місцем",
    open: "Відкрито",
    "in-progress": "В процесі",
    accepted: "Прийнято",
    delivery: "Доставка",
    escalated: "Ескаловано",
    urgent: "Терміново",
    "in progress": "В процесі",
    inactive: "Неактивний",
    rejected: "Відхилено",
    pending: "Очікує",
    "under review": "На розгляді",
    medium: "Середній",
    high: "Високий",
    maintenance: "Обслуговування",
    occupied: "Зайнято",
    "partially-occupied": "Частково Зайнято",
    "under-review": "На розгляді",
    pickup: "Забір",
    "pickup-delivery": "Самовивіз та Доставк",
    house: "Будинок",
    apartment: "Квартира",
    room: "Кімната",
    cancelled: "Скасовано",
  },
  ps: {
    confirmed: "تایید شوی",
    low: "ټیټ",
    completed: "بشپړ شوی",
    resolved: "حل شوی",
    approved: "منل شوی",
    active: "فعال",
    unoccupied: "خالي",
    "on-site": "په ځای کې",
    "off-site": "له ځایه بهر",
    open: "پرانيستل شوی",
    "in-progress": "پرمختګ کې دی",
    accepted: "منل شوی",
    delivery: "سپارنه",
    escalated: "لوړ شوی",
    urgent: "بیړنی",
    "in progress": "پرمختګ کې",
    inactive: "غیر فعال",
    rejected: "رد شوی",
    pending: "په تمه",
    "under review": "د بیاکتنې لاندې",
    medium: "منځنی",
    high: "لوړ",
    maintenance: "ساتنه",
    occupied: "نیول شوی",
    "partially-occupied": "یو څانګه نیول شوی",
    "under-review": "د بیاکتنې لاندې",
    pickup: "رااخیستل",
    "pickup-delivery": "اخیستل او سپارل",
    house: "کور",
    apartment: "اپارتمان",
    room: "کوټه",
    cancelled: "لغو شوی",
  },
};
